#2 fix export html code
OptimisticPessimist/language_learning_helper pull request #3
Opened 2019-12-06 16:51 UTC by OptimisticPessimist

## 改修点
- `_fetch_phonetics`
  - この関数内では改行処理を行わない
  - `<br>`タグを除去したあと、`[a-zA-Z0-9\']`に含まれない文字は正規表現で除去することにした
  - ``正規表現コスト削減目的でコンパイルするのは日本語ルビシステムと同じ意図（ただし計測はしていない）

- `_put_on`
  - 改行が含まれる文字列が渡されたとき、ソースコードも改行されるようにした
    - ソースコードの表示が若干綺麗になったが`<ruby>`タグを使う以上おぞましさに変わりはない
  - 辞書と一致しない単語が含まれていた場合は単語の後ろにスペースが追加されていなかったので修正した

2019-12-11 10:47 UTC, nafuka11 requested changes
README.mdのUsageのレビューです。

2019-12-11 10:47 UTC, nafuka11 commented on README.md
> +`config/sample.yaml` is prepared as a sample it.
READMEでは `config/sample.yaml` と表記されていますが、
実際のファイルパスは `config/sample_setting.yaml` となっています。

2019-12-11 10:47 UTC, nafuka11 commented on README.md
> +This causes `app.py` to read the settings in the `config/production.yaml` file.
`config/production.yaml` ではなく、 `config/development.yaml` ではないでしょうか。

2019-12-11 10:54 UTC, nafuka11 requested changes
Typo: Usage

2019-12-11 11:22 UTC, OptimisticPessimist commented on README.md
> +`config/sample.yaml` is prepared as a sample it.
たしかに。修正しました。

2019-12-12 04:25 UTC, nafuka11 reviewed
_fetch_phoneticsのレビューです。

2019-12-12 04:25 UTC, nafuka11 commented on src/english/ipa_phonetics.py
> +                target = word.replace("<br>", "")
export_htmlで\<br\>をjoinしなければ、この処理は不要になるのではないでしょうか。

2019-12-12 04:25 UTC, nafuka11 commented on src/english/ipa_phonetics.py
> +                target = re.sub(self.re_non_ascii, "", target)
例えば入力文字列\<text\>だと事前にエスケープされて `&lttext&gt` となり、
置換されて `lttextgt` となりKeyErrorが発生します。
これは意図通りの動作でしょうか。
（意図通りで無ければ、エスケープを変換する別メソッドを作ってもいいのかもしれません）

2019-12-12 04:25 UTC, nafuka11 commented on src/english/ipa_phonetics.py
> +        for sentence in sentences:
ネストが深すぎるように思います。
sentencesは全ての行が1要素に入っています。
sentencesのループは不要かと思います。
（入力行毎に_fetch_phoneticsした方が本当は良いと思います）

2019-12-12 07:02 UTC, OptimisticPessimist commented on src/english/ipa_phonetics.py
> +                target = word.replace("<br>", "")
`src/japanese/kana_phonetics.py`と処理をあわせたいので、リファクタリング時に考えます。

2019-12-12 07:03 UTC, OptimisticPessimist commented on src/english/ipa_phonetics.py
> +                target = re.sub(self.re_non_ascii, "", target)
意図通りじゃありませんね。
テストケース作った上で回避を考えます。

2019-12-12 07:07 UTC, OptimisticPessimist commented on src/english/ipa_phonetics.py
> +        for sentence in sentences:
このネストの深さは怒られる……。

"the"を区別する箇所は関数化して、他と処理を合わせるときにも内部から呼び出す形で使うようにしてネストを浅くします。深くなってる理由は母音の判定なので多分それで解決するはず。

2019-12-12 07:09 UTC, OptimisticPessimist commented on src/english/ipa_phonetics.py
> +        for sentence in sentences:
> 入力行毎に_fetch_phoneticsした方が本当は良い

これについては具体例書けますか？
スマートに書けるなら日本語のフリガナ処理も直したいです。

2019-12-12 07:22 UTC, nafuka11 commented on src/english/ipa_phonetics.py
> +        for sentence in sentences:
export_htmlで入力行毎にループし、
```python
def export_html(self, text_post: str) -> str:
    converted: List[str] = list()

    for sentence in text_post.splitlines():
        phonetics: List[Tuple[str, str]] = self._fetch_phonetics(sentence)
        converted.append(self._put_on(phonetics))

    return "".join(converted)
```
_fetch_phoneticsの引数sentences(List[str])をsentence(str)に。

_put_onは以下のようにすれば、行毎に対応できるかと思います。
```python
def _put_on(cls, words_list: List[Tuple[str, str]]) -> str:
    sentence: List[str] = list()

    for word, phonetics in words_list:
        if phonetics is not "":
            sentence.append(f'<ruby class="under">{word}'
                            f'<rp>[</rp><rt>{phonetics}</rt><rp>]</rp></ruby> ')
        else:
            sentence.append(f"{word} ")
    return "".join(sentence) + "<br>"
```

2019-12-12 08:18 UTC, OptimisticPessimist commented on src/english/ipa_phonetics.py
> +                target = re.sub(self.re_non_ascii, "", target)
回避できたので新たなissueは不要です。

2019-12-12 08:23 UTC, OptimisticPessimist commented on src/english/ipa_phonetics.py
> +        for sentence in sentences:
処理はそのままに`_distinguish_the`という関数に切り出してネストを浅くして対応しました。
日本語の処理と一緒にリファクタリングでどうするか考えるのを次のissueにします。

2019-12-13 01:37 UTC, nafuka11 commented on src/english/ipa_phonetics.py
> +                target = re.sub(self.re_non_ascii, "", target)
テストでは回避できていますが、実際には回避できていません。
テストケースではエスケープ後の文字列（ `<Vocal>` ではなく`&ltVocal&gt` ）を検証する必要があるかと思います。

2019-12-13 01:44 UTC, nafuka11 commented on src/english/ipa_phonetics.py
> +        for sentence in sentences:
メソッド名について提案です。
`_distinguish_the` では、発音記号の取得 + theの処理 を行なっています。
発音記号の取得がメインのため、`_fetch_phonetics_from_word` などとした方が適切ではないでしょうか。
（後々the以外の処理が入るとメソッド名と処理が一致しなくなりそうですし）

2019-12-19 02:05 UTC, merged